### PR TITLE
Make protobluff compatible with C++11 and protobuf >3.6

### PR DESCRIPTION
**Pull request by pperisin**
- replace 'scoped_ptr' and 'scoped_array' with 'std::unique_ptr'
- prepend 'std::' to 'vector'

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for your work on this! Why `C++11`? I assume this solves #3?

**Comment by pperisin** [comment]
Hi,

ummm... So this is my first pull request in github, and it has been a while when I was working on in C++. So consider this completely newbie pull request :).

In commits inside protobuf project I saw this commit message when scoped_ptr was removed:

    Deleted scoped_ptr.h
    
    We no longer need this, now that we have finished the switch to C++11
    and are using std::unique_ptr.

At the time I thought that meant that it is necessary to use C++11.
However, I have now tried without C++11 flag, and it works as well. So I can remove that part.

Yes, this seems to fix #3 . I was having same problems reported in there, and after this changes everything compiles fine. 

Regards,
Petar

**Comment by squidfunk** [comment]
@pperisin thanks! LGTM. Will merge into master and prepare a release.

**Comment by squidfunk** [comment]
Turns out `C++11` is necessary, as `protobluff-3.6+` relies on `std::call_once` et. al., but that's okay. The generator now compiles with `protobuf-3.6`, but not with `protobuf-3.7`, due to the following error:

```
Making all in generator
  CXX      protoc_gen_protobluff-enum.o
  CXX      protoc_gen_protobluff-enum_value.o
  CXX      protoc_gen_protobluff-extension.o
  CXX      protoc_gen_protobluff-field.o
  CXX      protoc_gen_protobluff-file.o
  CXX      protoc_gen_protobluff-generator.o
  CXX      protoc_gen_protobluff-message.o
  CXX      protoc_gen_protobluff-oneof.o
  CXX      protoc_gen_protobluff-protoc-gen-protobluff.o
  CXX      protoc_gen_protobluff-strutil.o
strutil.cc:242:3: error: use of undeclared identifier 'GOOGLE_CHECK'
  GOOGLE_CHECK(result != NULL);
  ^
strutil.cc:306:3: error: use of undeclared identifier 'GOOGLE_DCHECK'
  GOOGLE_DCHECK(errors == NULL) << "Error reporting not implemented.";
  ^
strutil.cc:321:22: error: use of undeclared identifier 'ERROR'
          LOG_STRING(ERROR, errors) << "String cannot end with \\";
                     ^
strutil.cc:348:26: error: use of undeclared identifier 'ERROR'
              LOG_STRING(ERROR, errors) << "String cannot end with \\x";
                         ^
strutil.cc:350:26: error: use of undeclared identifier 'ERROR'
              LOG_STRING(ERROR, errors) <<
                         ^
strutil.cc:360:24: error: use of undeclared identifier 'ERROR'
            LOG_STRING(ERROR, errors) << "Value of " <<
                       ^
strutil.cc:413:22: error: use of undeclared identifier 'ERROR'
          LOG_STRING(ERROR, errors) << "Unknown escape sequence: \\" << *p;
                     ^
strutil.cc:444:3: error: use of undeclared identifier 'GOOGLE_CHECK'
  GOOGLE_CHECK(dest);
  ^
strutil.cc:531:3: error: use of undeclared identifier 'GOOGLE_DCHECK_GE'
  GOOGLE_DCHECK_GE(len, 0);
  ^
strutil.cc:542:3: error: use of undeclared identifier 'GOOGLE_DCHECK_GE'
  GOOGLE_DCHECK_GE(len, 0);
  ^
strutil.cc:551:3: error: use of undeclared identifier 'GOOGLE_DCHECK_GE'
  GOOGLE_DCHECK_GE(len, 0);
  ^
strutil.cc:696:3: error: use of undeclared identifier 'GOOGLE_CHECK'
  GOOGLE_CHECK(i >= 0) << "FastHexToBuffer() wants non-negative integers, not " << i;
  ^
strutil.cc:875:3: error: use of undeclared identifier 'GOOGLE_DCHECK_LT'
  GOOGLE_DCHECK_LT(digits, 100);
  ^
strutil.cc:1064:3: error: use of undeclared identifier 'GOOGLE_DCHECK'
  GOOGLE_DCHECK(snprintf_result > 0 && snprintf_result < kDoubleToBufferSize);
  ^
strutil.cc:1078:5: error: use of undeclared identifier 'GOOGLE_DCHECK'
    GOOGLE_DCHECK(snprintf_result > 0 && snprintf_result < kDoubleToBufferSize);
    ^
strutil.cc:1113:3: error: use of undeclared identifier 'GOOGLE_DCHECK'
  GOOGLE_DCHECK(snprintf_result > 0 && snprintf_result < kFloatToBufferSize);
  ^
strutil.cc:1121:5: error: use of undeclared identifier 'GOOGLE_DCHECK'
    GOOGLE_DCHECK(snprintf_result > 0 && snprintf_result < kFloatToBufferSize);
    ^
strutil.cc:1144:3: error: use of undeclared identifier 'GOOGLE_CHECK_EQ'
  GOOGLE_CHECK_EQ(temp[0], '1');
  ^
strutil.cc:1145:3: error: use of undeclared identifier 'GOOGLE_CHECK_EQ'
  GOOGLE_CHECK_EQ(temp[size-1], '5');
  ^

```

I can't find where `GOOGLE_CHECK` and the other macros are defined. Any ideas?

BTW: great first PR!

**Comment by pperisin** [comment]
Hey, seems like C++11 is needed! I don't have to fix it any more :D

I had problems since I amended commit, and tried to push again, and remote rejected the push. I'm kinda used to gerrit review, this is kinda new to me. :D

Thanks for compliment about first PR :D


Now, from what I can see in protobuf, I believe GOOGLE_CHECK is defined in:

    _protobuf/src/google/protobuf/stubs/logging.h_

So it is in _logging.h_ file, which is in same folder where _scoped_ptr_ (removed in this commit) used to be.

I just checked out 3.7 code (did not try to compile it yet), and it seems like it has definition for GOOGLE_CHECK in that file in version 3.7

**Comment by squidfunk** [comment]
Awesome! This fixes it for 3.7+. Will issue a new release in a few minutes.

**Comment by pperisin** [comment]
Great!

I noticed that in CHANGELOG file there is wrong month: (2019-06-11) instead of (2019-07-11)

This is completely irrelevant to me, just noticed it and wanted to let you know. :)

Thanks for help with review and formatting in this issue :)

**Comment by squidfunk** [comment]
Corrected it. Thanks for your help on this issue!
